{
 "title": "Impfrate",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bundesland",
    "label": "Bundesland",
    "query": "select bundesland from bundesland"
   }
  ]
 },
 "panels": [
  {
   "title": "Erklärung",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Die Impfrate zeigt an wie viel Prozent der Personen geimpft sind. Unter \"Impfbare Bevölkerung\" werden alle Personen ab 12 Jahren erfasst. \"Gesamtbevölkerung\" enthält alle Personen. Die \"relative Impfgeschwindigkeit\" ist der Anteil der Bevölkerung, der in den letzten 7 Tagen geimpft wurde.\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  inz_faelle_7d\nFROM timeline_bezirke\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Impfrate 1. Dosis",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select *\nfrom impfraten_over_bundesland(1);"
    }
   ]
  },
  {
   "title": "Impfrate 2. Dosis",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select *\nfrom impfraten_over_bundesland(2);"
    }
   ]
  },
  { "title": "$bundesland", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "bundesland" },
  {
   "title": "Impfrate 1. Dosis nach Altersgruppen",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "with bl as (\n  select bid as bl_bid\n  from bundesland\n  where bundesland = $bundesland\n)\nSELECT\n  date AS \"time\", gruppe::text as metric, impfrate\nFROM impfraten, bl\nWHERE\n  $__timeFilter(date) and bid=bl_bid and geschlecht='Alle Geschlechter' and impfstoff='Alle Impfstoffe' and dosis=1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Impfrate 2. Dosis nach Altersgruppen",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "with bl as (\n  select bid as bl_bid\n  from bundesland\n  where bundesland = $bundesland\n)\nSELECT\n  date AS \"time\", gruppe::text as metric, impfrate\nFROM impfraten, bl\nWHERE\n  $__timeFilter(date) and bid=bl_bid and geschlecht='Alle Geschlechter' and impfstoff='Alle Impfstoffe' and dosis=2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Relative Impfgeschwindigkeit 1. Dosis nach Altersgruppe",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "with bl as (\n  select bid as bl_bid\n  from bundesland\n  where bundesland = $bundesland\n)\nSELECT\n  date AS \"time\", gruppe::text as metric, impfrate_7d\nFROM impfraten, bl\nWHERE\n  $__timeFilter(date) and bid=bl_bid and geschlecht='Alle Geschlechter' and impfstoff='Alle Impfstoffe' and dosis=1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Relative Impfgeschwindigkeit 2. Dosis nach Altersgruppe",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "with bl as (\n  select bid as bl_bid\n  from bundesland\n  where bundesland = $bundesland\n)\nSELECT\n  date AS \"time\", gruppe::text as metric, impfrate_7d\nFROM impfraten, bl\nWHERE\n  $__timeFilter(date) and bid=bl_bid and geschlecht='Alle Geschlechter' and impfstoff='Alle Impfstoffe' and dosis=2\nORDER BY 1"
    }
   ]
  }
 ]
}