{
 "title": "Inzidenz",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bezirk", "label": "Bezirk", "query": "select bezirk from bezirk" },
   {
    "name": "bundesland",
    "label": "Bundesland",
    "query": "select bundesland from bundesland"
   },
   { "name": "inzidenz_days", "label": "Inzidenz Tage", "query": "1,2,3,4,5,6,7,10,14,20,30" },
   { "name": "per_capita", "label": "Per capita", "query": "1000,100000,1000000" },
   { "name": "delta_days", "label": "Veränderung Glättung Tage", "query": "1,2,3,4,5,6,7,10,14,20,30" }
  ]
 },
 "panels": [
  { "title": "${inzidenz_days} Tage Inzidenz", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inzidenz (pro $per_capita Einwohner)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  region AS metric,\n  inzidenz\nFROM inzidenz($inzidenz_days, $per_capita, $delta_days)\nWHERE\n  $__timeFilter(date) AND\n  (region IN (SELECT * FROM json_array_elements_text('${bezirk:json}')) OR region IN (SELECT * FROM json_array_elements_text('${bundesland:json}'))) = 'true'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "$inzidenz_days Tage Inzidenz (pro $per_capita Einwohner)",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  region AS metric,\n  inzidenz\nFROM inzidenz($inzidenz_days, $per_capita, $delta_days)\nWHERE\n  $__timeFilter(date) AND\n  (region IN (SELECT * FROM json_array_elements_text('${bezirk:json}')) OR region IN (SELECT * FROM json_array_elements_text('${bundesland:json}'))) = 'true'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Veränderung ${inzidenz_days} Tage Inzidenz",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Tägliche Veränderung Inzidenz ($delta_days Tage Durchschnitt)",
   "type": "graph",
   "description": "Tägliche Veränderung 7 Tage Inzidenz (über $deltaaverage Tage)",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  region AS metric,\n  inzidenz_increase_daily_percent\nFROM inzidenz($inzidenz_days, $per_capita, $delta_days)\nWHERE\n  $__timeFilter(date) AND\n  (region IN (SELECT * FROM json_array_elements_text('${bezirk:json}')) OR region IN (SELECT * FROM json_array_elements_text('${bundesland:json}'))) = 'true'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Tägliche Veränderung $inzidenz_days Tage Inzidenz (letzte $delta_days Tage)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  region AS metric,\n  inzidenz_increase_daily_percent\nFROM inzidenz($inzidenz_days, $per_capita, $delta_days)\nWHERE\n  $__timeFilter(date) AND\n  (region IN (SELECT * FROM json_array_elements_text('${bezirk:json}')) OR region IN (SELECT * FROM json_array_elements_text('${bundesland:json}'))) = 'true'\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Tabellen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Bezirke",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (region)\n  region AS \"Bezirk\",\n  inzidenz as \"Inzidenz $inzidenz_days Tage\",\n  inzidenz_increase_daily_percent as \"Täglicher Anstieg %\",\n  anz_faelle as \"Fälle $inzidenz_days Tage\"\nFROM inzidenz($inzidenz_days, $per_capita, $delta_days)\nWHERE\n  $__timeFilter(date) AND \n  typ = 'b'\nORDER BY region ASC, date DESC"
    }
   ]
  },
  {
   "title": "Bundesländer",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (region)\n  region AS \"Bundesland\",\n  inzidenz as \"Inzidenz $inzidenz_days Tage\",\n  inzidenz_increase_daily_percent as \"Täglicher Anstieg %\",\n  anz_faelle as \"Fälle $inzidenz_days Tage\"\nFROM inzidenz($inzidenz_days, $per_capita, $delta_days)\nWHERE\n  $__timeFilter(date) AND \n  typ = 'l'\nORDER BY region ASC, date DESC"
    }
   ]
  }
 ]
}