{
 "title": "COVID 19 Dashboard Österreich",
 "time": { "from": "now-120d", "to": "now" },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# COVID-19 Dashboard Österreich\n\n## - [Inzidenz](/d/c664EFpGk/inzidenz)</h2>\n## - [Fälle](/d/9778YUpGz/falle)</h2>\n## - [Hospitalisierung](/d/aXA0yo2Gz/hospitalisierung)</h2>\n## - [Prognose](/d/o6AcbYTMk/fallzahlen-prognose)</h2>   \n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  inz_faelle_7d\nFROM timeline_bezirke\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "7 Tage Inzidenz",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  date AS \"time\",\n  region AS metric,\n  inzidenz\nFROM inzidenz(7, 100000, 1, get_rids('[\"Burgenland\", \"Kärnten\", \"Niederösterreich\", \"Oberösterreich\", \"Salzburg\", \"Steiermark\", \"Tirol\",\"Vorarlberg\", \"Wien\"]', '[]'))\nWHERE\n  date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "7 Tage Inzidenz Österreich",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  region AS metric,\n  inzidenz\nFROM inzidenz(7, 100000, 1, get_rids('[\"Österreich\"]', '[]'))\nWHERE\n  date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Intensivstation Österreich",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  fz_icu as \"ICU Fallzahl\",\n  fz_icu_free + fz_icu as \"ICU Kapazität\",\n  (fz_icu::float / (fz_icu_free + fz_icu)) * 100 as \"ICU Auslastung %\"\nFROM fallzahlen\nWHERE\n  date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}'\n  AND bundesland = 'Österreich'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Prognose Fallzahlen Österreich",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT date as time, value, lo95, lo80, forecast, hi80, hi95\nFROM faelle_prediction()\nWHERE\n  date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}'::date + 14\nORDER BY 1"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "# Anmerkungen\n\nDie Daten in diesem Dashboard stammen von [OpenData/AGES](https://www.data.gv.at/covid-19/) und werden täglich um 14:30 aktualisiert.\n\nEs wird keine Gewähr für die Richtigkeit der Daten in diesem Dashboard übernommen, noch werden die Daten selbst von uns auf ihre Richtigkeit überprüft. \n\nDieses Dashboard ist Open Source: [GitHub](https://github.com/andi0b/cvdashboard)\n\n## Impressum\nFirma greenwasp GmbH <br/>\nFN: 399041a, Landesgericht Eisenstadt <br/>\nKontaktdaten/Unternehmensgegenstand: siehe [www.greenwasp.at](http://greenwasp.at)"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  inz_faelle_7d\nFROM timeline_bezirke\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  }
 ]
}