version: "3.3"

services:

  grafana:
    image: grafana/grafana:9.0.3
    restart: always
    environment:
      - GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GRAFANA_POSTGRES_USER=${GRAFANA_POSTGRES_USER:-postgres}
      - GRAFANA_POSTGRES_PASSWORD=${GRAFANA_POSTGRES_PASSWORD:-postgres}

    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./grafana-provisioning:/etc/grafana/provisioning"
      - "./grafana-provisioning/grafana.ini:/etc/grafana/grafana.ini"

  db:
    image: ghcr.io/andi0b/cvdashboard-postgres-r
    build:
      context: postgres-r/
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - "./data:/data"
      - "./db:/db"

  import-data-service:
    image: ghcr.io/andi0b/cvdashboard-import-data-service
    build:
      context: import-data-service/
    
    environment:
      - PGUSER=${POSTGRES_USER:-postgres}
      - PGPASSWORD=${POSTGRES_PASSWORD:-postgres}

    volumes:
      - "./data:/data"
      - "./db:/db"
      - "./scripts:/scripts"

