version: "3.8"

services:

  grafana:
    image: grafana/grafana:7.2.1
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./grafana-provisioning:/etc/grafana/provisioning"
      - "./grafana-provisioning/grafana.ini:/etc/grafana/grafana.ini"

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./data:/data"
      - "./db:/db"
