version: "3.3"

services:

  grafana:
    image: grafana/grafana:8.0.3
    restart: always
    environment:
      - GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GRAFANA_POSTGRES_USER=${GRAFANA_POSTGRES_USER:-postgres}
      - GRAFANA_POSTGRES_PASSWORD=${GRAFANA_POSTGRES_PASSWORD:-postgres}

    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./grafana-provisioning:/etc/grafana/provisioning"
      - "./grafana-provisioning/grafana.ini:/etc/grafana/grafana.ini"

  db:
    build:
      context: postgres-r/
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - "./data:/data"
      - "./db:/db"

  pgpool:
    image: bitnami/pgpool:4
    restart: always
    environment:
      - PGPOOL_BACKEND_NODES=0:db:5432
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_SR_CHECK_USER=${POSTGRES_USER:-postgres}
      - PGPOOL_SR_CHECK_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGPOOL_POSTGRES_USERNAME=${POSTGRES_USER:-postgres}
      - PGPOOL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGPOOL_ADMIN_USERNAME=${POSTGRES_USER:-postgres}
      - PGPOOL_ADMIN_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGPOOL_USER_CONF_FILE=/config/pgpool.conf
    volumes:
      - "./pgpool.conf:/config/pgpool.conf"

  import-data-service:
    build:
      context: import-data-service/
    
    environment:
      - PGUSER=${POSTGRES_USER:-postgres}
      - PGPASSWORD=${POSTGRES_PASSWORD:-postgres}

    volumes:
      - "./data:/data"
      - "./db:/db"
      - "./scripts:/scripts"

