version: "3.8"

services:

  grafana:
    image: grafana/grafana:7.3.4
    environment:
      - GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GRAFANA_POSTGRES_USER=${GRAFANA_POSTGRES_USER:-postgres}
      - GRAFANA_POSTGRES_PASSWORD=${GRAFANA_POSTGRES_PASSWORD:-postgres}

    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./grafana-provisioning:/etc/grafana/provisioning"
      - "./grafana-provisioning/grafana.ini:/etc/grafana/grafana.ini"

  db:
    build:
      context: postgres-r/
    #image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./data:/data"
      - "./db:/db"

  import-data-service:
    build:
      context: import-data-service/
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

    volumes:
      - "./data:/data"
      - "./db:/db"

