version: "3.8"

services:

  grafana:
    image: grafana/grafana:7.2.1
    ports:
      - "3000:3000"
    volumes:
      - "./data/grafana:/var/lib/grafana"
      - "./grafana-provisioning:/etc/grafana/provisioning"

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/data"
      - "./db:/db"
