apiVersion: v1
kind: Service
metadata:
  labels:
    app: cvdashboard
  name: cvdashboard
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: cvdashboard
  sessionAffinity: None
  type: ClusterIP
