\i 00_create_tables.sql
\i 01_create_functions.sql
\i 02_plr.sql
\i 10_import_data.sql
\i 11_import_impfung.sql
\i 15_calculate_groups.sql
\i 20_extract_stammdaten.sql
\i 25_refresh_views.sql
\i 30_create_users_permissions.sql